profiles:
  1bde83c5-465f-40d2-96cb-aed9b0685e1b:
    age: null
    children:
    - 4413deef-1ead-40cd-90e0-03a24fdb6eaa
    dna_profile:
      Amelogenin:
      - X
      - Y
      CSF1PO:
      - '11'
      - '12'
      D10S1248:
      - '14'
      - '17'
      D12S391:
      - '19'
      - '20'
      D13S317:
      - '8'
      - '12'
      D16S539:
      - '11'
      - '12'
      D18S51:
      - '14'
      - '14'
      D19S433:
      - '12'
      - '13'
      D1S1656:
      - '14'
      - '16'
      D21S11:
      - '30'
      - '30.2'
      D22S1045:
      - '14'
      - '17'
      D2S1338:
      - '19'
      - '25'
      D2S441:
      - '11'
      - '14'
      D3S1358:
      - '16'
      - '17'
      D5S818:
      - '11'
      - '12'
      D7S820:
      - '8'
      - '8'
      D8S1179:
      - '12'
      - '14'
      FGA:
      - '21'
      - '27'
      TH01:
      - '8'
      - '9'
      TPOX:
      - '9'
      - '10'
      VWA:
      - '15'
      - '16'
    name: null
    parents: []
    sex: M
    siblings: []
