profiles:
  ed323128-9695-4eab-93a5-46ca1009bdda:
    age: null
    children: []
    dna_profile:
      Amelogenin:
      - X
      - X
      CSF1PO:
      - '10'
      - '13'
      D10S1248:
      - '13'
      - '14'
      D12S391:
      - '18'
      - '19'
      D13S317:
      - '11'
      - '13'
      D16S539:
      - '10'
      - '12'
      D18S51:
      - '15'
      - '15'
      D19S433:
      - '12'
      - '14'
      D1S1656:
      - '12'
      - '13'
      D21S11:
      - '27'
      - '29'
      D22S1045:
      - '16'
      - '16'
      D2S1338:
      - '16'
      - '17'
      D2S441:
      - '12'
      - '15'
      D3S1358:
      - '15'
      - '16'
      D5S818:
      - '12'
      - '13'
      D7S820:
      - '8'
      - '9'
      D8S1179:
      - '14'
      - '16'
      FGA:
      - '20'
      - '21'
      TH01:
      - '7'
      - '9'
      TPOX:
      - '8'
      - '8'
      VWA:
      - '17'
      - '18'
    name: null
    parents: []
    sex: F
    siblings: []
