profiles:
  c9be4da8-c29c-4500-8619-780d265be818:
    age: null
    children: []
    dna_profile:
      Amelogenin:
      - X
      - Y
      CSF1PO:
      - 9
      - 9
      D10S1248:
      - 12
      - 10
      D12S391:
      - 16
      - 15
      D13S317:
      - 9
      - 8
      D16S539:
      - 15
      - 9
      D18S51:
      - 25
      - 12
      D19S433:
      - 13
      - 9
      D1S1656:
      - 19
      - 16
      D21S11:
      - 26
      - 25
      D22S1045:
      - 14
      - 9
      D2S1338:
      - 23
      - 19
      D2S441:
      - 14
      - 10
      D3S1358:
      - 15
      - 15
      D5S818:
      - 9
      - 8
      D7S820:
      - 11
      - 8
      D8S1179:
      - 17
      - 12
      FGA:
      - 30
      - 19
      THO1:
      - 13
      - 11
      TPOX:
      - 10
      - 8
      VWA:
      - 15
      - 13
    name: null
    parents: []
    sex: null
    siblings: []
